### ISSUE TITLE
Pay With Card

### ISSUE THREAD

**Issue by Elkelany84** [ahmedhosni803/flutter_paymob#2]
Thanks for your effort,but the Pay with card is not working,when i try test test card it DECLINED..and there are no info in the payment section in the paymob dashboard
![Untitled](https://github.com/ahmedhosni803/flutter_paymob/assets/74449997/1efe3803-a39c-410e-b402-171c40212984)

**Comment by ahmedhosni803** [comment]
You must contact Paymob support in order for it to be activated for you
